### ISSUE TITLE
ДАМЫ И ГОСПОДА

### ISSUE THREAD

**Issue by ca4tuk** [aminobotskek/dmarcly#1]
РЫГАЛИ ВСЕ

**Comment by l0v3m0n3y** [comment]
Я твою мать трахал :)

**Comment by ca4tuk** [comment]
долбоеб пройди курс от дударя выучи питон за час хули ты как дебил

**Comment by ca4tuk** [comment]
сука я такие ужасы читал три года назад в питон бегиннерах реально ходи оглядывайся за такое рано или поздно ебало разобьют

**Comment by ca4tuk** [comment]
не то что питонисты тебя просто любой кент за такую жижу в коде кошмарить будет друг

**Comment by l0v3m0n3y** [comment]
Чего тебе не нравится жертва ты аборта ?

**Comment by ca4tuk** [comment]
сука из мною написанных сообщений где я наглядно демонстрирую доминирование в твоем семейном древе над твоей матерью можно было понять что мне твой код не нравится

**Comment by ca4tuk** [comment]
сынуля

**Comment by l0v3m0n3y** [comment]
Хохлу слова не давали .

**Comment by ca4tuk** [comment]
кодить научись сука я сюда арабов нагоню они репо зарепортят ууу

**Comment by l0v3m0n3y** [comment]
Глотни спермы хохол
